book: 
  chapters:
    - index.qmd
    - part: "Network Fundamentals"
      chapters: 
        - chapters/01-networkrepresentations.qmd
    - part: "Measuring Networks"
    - part: "Real-World Networks"
    - part: "Models of Networks"
    - part: "Applications and Extensions"
    
