book: 
  chapters:
    - index.qmd
    - part: "Network Fundamentals"
      chapters: 
        - chapters/01-networkrepresentations.qmd
        - chapters/02-degree-walks-paths.qmd
        - chapters/03-components-laplacian.qmd
        - chapters/04-centrality.qmd
        - chapters/05-viz.qmd
        - chapters/07-real-world.qmd
    - part: "Models of Networks"
      chapters:
          - chapters/09-random-graphs.qmd
          - chapters/10-configuration-model.qmd
          - chapters/11-generating-functions.qmd
          - chapters/120-preferential-attachment.qmd
    - part: "Network Algorithms"
      chapters:
        - chapters/06-modularity.qmd
        - chapters/13-modularity-maximization.qmd
        - chapters/19-spectral-clustering.qmd
        - chapters/41-link-prediction.qmd
    - part: "Applications and Extensions"
      chapters:
        - chapters/50-random-walks.qmd
        - chapters/51-agent-based-modeling.qmd
        - chapters/52-epidemiology.qmd
    - part: "Appendices"
      appendices: 
        - chapters/99-resources.qmd    
