book: 
  chapters:
    - index.qmd
    - part: "Network Fundamentals"
      chapters: 
        - source/01-networkrepresentations.qmd
        - source/02-degree-walks-paths.qmd
        - source/03-components-laplacian.qmd
        - source/04-centrality.qmd
        - source/05-viz.qmd
        - source/07-real-world.qmd
    - part: "Models of Networks" 
      chapters: 
        - source/09-random-graphs.qmd 
        - source/10-configuration-model.qmd
        - source/11-generating-functions.qmd
        - source/120-preferential-attachment.qmd
    - part: "Network Algorithms"
      chapters:
        - source/06-modularity.qmd
        - source/13-modularity-maximization.qmd
        - source/19-spectral-clustering.qmd
        - source/41-link-prediction.qmd
    - part: "Applications and Extensions"
      chapters:
        - source/50-random-walks.qmd
        - source/51-agent-based-modeling.qmd
        - source/53-epidemiology-computational.qmd
        - source/52-epidemiology.qmd
  appendices:
    - source/92-probability.qmd
    - source/99-resources.qmd
code-summary: "Show code"
