book: 
  chapters:
    - index.qmd
    - part: "Network Fundamentals"
      chapters: 
        - source/01-networkrepresentations.qmd
        - source/02-degree-walks-paths.qmd
        - source/03-components-laplacian.qmd
    - part: "Measuring Networks"
      chapters: 
        - source/04-centrality.qmd
        - source/05-viz.qmd
        - source/06-modularity.qmd
    - part: "Real-World Networks"
      chapters: 
        - source/07-real-world.qmd
        - source/08-power-laws.qmd
    - part: "Models of Networks" 
      chapters: 
        - source/09-random-graphs.qmd 
        - source/10-configuration-model.qmd
        - source/11-generating-functions.qmd
    - part: "Network Algorithms"
      chapters:
        - source/13-modularity-maximization.qmd
        - source/19-spectral-clustering.qmd
        - source/41-link-prediction.qmd
    - part: "Applications and Extensions"
      chapters:
        - source/50-random-walks.qmd
code-summary: "Show code"
