book: 
  chapters:
    - index.qmd
    - part: "Network Fundamentals"
      chapters: 
        - chapters/01-networkrepresentations.qmd
        - chapters/02-degree-walks-paths.qmd
        - chapters/03-components-laplacian.qmd
    - part: "Measuring Networks"
      chapters: 
        - chapters/04-centrality.qmd
        - chapters/05-viz.qmd
        - chapters/06-modularity.qmd
    - part: "Real-World Networks"
      chapters: 
        - chapters/07-real-world.qmd
        - chapters/08-power-laws.qmd
    - part: "Models of Networks"
      chapters:
        - chapters/09-random-graphs.qmd
        - chapters/10-configuration-model.qmd
        - chapters/11-generating-functions.qmd
    - part: "Network Algorithms"
      chapters:
        - chapters/13-modularity-maximization.qmd
        - chapters/19-spectral-clustering.qmd
        - chapters/41-link-prediction.qmd
    - part: "Applications and Extensions"
    
