book: 
  chapters:
    - index.qmd
    - part: "Network Fundamentals"
      chapters: 
        - chapters/01-networkrepresentations.qmd
        - chapters/02-degree-walks-paths.qmd
        - chapters/03-components-laplacian.qmd
    - part: "Measuring Networks"
      chapters: 
        - chapters/04-centrality.qmd
        - chapters/05-viz.qmd
        - chapters/06-modularity.qmd
    - part: "Real-World Networks"
      chapters: 
        - chapters/30-real-world.qmd
        - chapters/31-power-laws.qmd
    - part: "Models of Networks"
    - part: "Applications and Extensions"
    
