book: 
  chapters:
    - index.qmd
    - part: "Network Fundamentals"
      chapters: 
        - source/01-example.qmd
    - part: "Measuring Networks"
      chapters: 
        - source/02-example.qmd 
        - source/03-example.qmd 
    - part: "Real-World Networks"
      chapters: 
        - source/04-example.qmd
    - part: "Models of Networks"
      chapters: 
        - source/05-example.qmd 
    
