# Welcome {.unnumbered}

This is a set of notes developed for an undergraduate course in network science. The target audience for these notes are undergraduates in mathematics and computer science who have completed courses in linear algebra, discrete mathematics, and programming. 

These notes are a collaborative project by Dr. [Heather Zinn Brooks](https://sites.google.com/g.hmc.edu/hzinnbrooks) (Department of Mathematics, Harvey Mudd College) and Dr. [Phil Chodrow](https://www.philchodrow.prof) (Department of Computer Science, Middlebury College).

## Pedagogical Features {.unnumbered}

These notes are explicitly designed for undergraduate instruction with students who are interested in and fluent in both mathematics and computation. For this reason: 

- Computational examples are integrated into the text and shown throughout. 
- Live versions of lecture notes are supplied as Jupyter Notebooks which can be opened in Google Colab. Certain code components have been removed. The purpose is to facilitate live-coding in lectures. 

### Source Text {.unnumbered}

The notes draw on a variety of sources which are noted in the References section of each page. We designed the overall sequence of notes to align with a course that uses @newman2018networks as a primary text.


### Use and Reuse {.unnumbered}

These notes are free to reuse and adapt for educational purposes. Attribution is appreciated but not required. 

## Acknowledgements {.unnumbered}

This site was generated using the [Quarto](https://quarto.org/) publishing system. It is hosted on GitHub and published via GitHub Pages. We thank Mason Porter for inspiration in earlier versions of this course. 

We thank the National Science Foundation's Division of Applied Mathematics for support to both HZB (grant DMS-2109239) and PSC (grant DMS-2407058).

## References {.unnumbered}


